development:
  adapter: mysql
  encoding: utf8
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE"] %>
  host: <%= ENV["DATABASE_HOST"] %>
production:
  adapter: mysql
  encoding: utf8
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE"] %>
  host: <%= ENV["DATABASE_HOST"] %>
